# Generated by Django 3.2.8 on 2022-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0002_auto_20220107_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='faculty',
            field=models.CharField(choices=[('Computing', 'Computing'), ('Networking', 'Networking'), ('Multimedia', 'Multimedia')], max_length=50, null=True),
        ),
    ]
