# Generated by Django 3.2.8 on 2022-01-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0003_alter_club_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emeraldApp.club'),
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emeraldApp.club'),
        ),
        migrations.AddField(
            model_name='president',
            name='club_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emeraldApp.club'),
        ),
    ]
