# Generated by Django 3.2.8 on 2022-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0005_alter_event_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timing',
            field=models.TimeField(max_length=30, null=True),
        ),
    ]
