# Generated by Django 3.2.8 on 2022-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0006_alter_event_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
