# Generated by Django 3.2.7 on 2022-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0007_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(choices=[('General Member', 'General Member'), ('President', 'President'), ('Vice President', 'Vice President'), ('Event Manager', 'Event Manager'), ('Treasurer', 'Treasurer')], max_length=40, null=True),
        ),
    ]
