# Generated by Django 3.2.7 on 2022-02-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0012_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
