# Generated by Django 3.2.7 on 2022-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0015_member_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('club', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to=''),
        ),
    ]
