# Generated by Django 3.2.7 on 2022-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0016_auto_20220226_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipants',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
