# Generated by Django 3.2.7 on 2022-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0019_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, null=True)),
                ('picture', models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='')),
            ],
        ),
    ]
