# Generated by Django 3.2.7 on 2022-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emeraldApp', '0020_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emeraldApp.club'),
        ),
    ]
